controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

# Redirect the root URL to /livre
_livre_redirect:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: app_livre_index
    permanent: true
